export default {
	CART_REQUEST: "DELIVERY_CART_REQUEST",
	CART_ERROR  : "DELIVERY_CART_ERROR",
	CART_SUCCESS: "DELIVERY_CART_SUCCESS",

	CART_RESET: "DELIVERY_CART_RESET",

	SELECT_ADDRESS     : "DELIVERY_SELECT_ADDRESS",
	ENTER_STORE        : "DELIVERY_ENTER_STORE",
	RESET_ADDRESS      : "DELIVERY_RESET_ADDRESS",
	SAVE_NUMBER_ADDRESS: "DELIVERY_SAVE_NUMBER_ADDRESS",
};
