export default {
	NOTIFICATION_ON : "GENERAL_NOTIFICATION_ON",
	NOTIFICATION_OFF: "GENERAL_NOTIFICATION_OFF",

	TYPES: "GENERAL_TYPES",
	SETTING_WHATSAPP: "SETTING_WHATSAPP",
	
	REDIRECT_TO: "GENERAL_REDIRECT_TO",
};
